### ISSUE TITLE
Crendentials, HTTPS y morgan

### ISSUE THREAD

**Issue by ferborva** [tomasvrubio/miTUBE#1]
Hola Tomas!!!
proyectazo el que tienes aqui en carrillado ;) AWESOME! hehehe

Un par de cosillas que te dejo como coments para ver si te viene bien:
- Credentials y demas secret data no lo meteria en un archivo. Pasalo como variables de entorno y pillalas dentro de la app desde `process.env.<>`
- Igual te molaria probar a subir este proyecto a glitch. com, te da https host para que puedas hacer pruebas. Como estas con mongo, en lugar de montar una base de datos en local puedes hacerte una sandbox gratuita en mlabs (https://mlab.com/plans/pricing/#plan-type=sandbox)
- Morgan lo metes en dos lineas ;) no lo tengas en TODOs de tu readme

Quiero URL soon!!! :D

**Comment by tomasvrubio** [comment]
Credentials en el entorno del usuario y morgan te prometo que los meto pronto. Lo de glitch te lo agradezco pero al utilizar bastante ancho de banda con las descargas y subidas de canciones y que es un poco sparrow lo que ando haciendo me da que no lo puedo utilizar. Pero para el próximo proyecto que tengo en mente si!!
