### ISSUE TITLE
icon for miTuBE

### ISSUE THREAD

**Issue by somratking420** [tomasvrubio/miTUBE#2]
hi @tomasvrubio  , I am a graphic designer, I want to help you in graphic design.

After I review your project, your app is very good. Therefore I suggest a new logo and icon for you. If you want it, I will design it for you and it's free

**Comment by tomasvrubio** [comment]
Hi @somratking420. It would be amazing. Now I'm working in the backend of the app so I'm not worrying about the part of access and visual so what I have done is ugly.

I'm waiting to see what can you do :).

Thanks
